// Run: node seedResources.js
// Seeds the resource library with quality starter resources

import dotenv from "dotenv";
dotenv.config();

import mongoose from "mongoose";
import Resource from "./models/Resource.model.js";
import User from "./models/User.model.js";

await mongoose.connect(process.env.MONGO_URI);
console.log("Connected to MongoDB ✅");

// Find an admin user to be the submitter
let admin = await User.findOne({ role: "admin" });
if (!admin) admin = await User.findOne(); // fallback to first user
const adminId = admin._id;

const RESOURCES = [
  // ── Technology ──────────────────────────────────────────────────
  { title: "CS50 by Harvard", url: "https://cs50.harvard.edu/x", description: "The most popular intro to Computer Science course in the world. Free, rigorous, and beginner-friendly. Covers C, Python, SQL, JavaScript and more.", field: "Technology", category: "Course", difficulty: "Beginner", isFree: true, tags: ["CS Fundamentals", "Python", "C", "Harvard"], isPinned: true },
  { title: "The Odin Project", url: "https://www.theodinproject.com", description: "A free, open-source full stack web development curriculum. Covers HTML, CSS, JavaScript, React, Node.js from scratch with hands-on projects.", field: "Technology", category: "Course", difficulty: "Beginner", isFree: true, tags: ["Web Development", "Full Stack", "JavaScript"] },
  { title: "LeetCode", url: "https://leetcode.com", description: "The most popular platform for coding interview preparation. 2500+ problems covering DSA, system design, and SQL. Essential for FAANG interviews.", field: "Technology", category: "Practice", difficulty: "Intermediate", isFree: true, tags: ["DSA", "Interview Prep", "Algorithms"] },
  { title: "Roadmap.sh", url: "https://roadmap.sh", description: "Community-built visual roadmaps for becoming a developer. Covers Frontend, Backend, DevOps, Android, AI, and 20+ other paths.", field: "Technology", category: "Tool", difficulty: "Beginner", isFree: true, tags: ["Career Roadmap", "Web Dev", "DevOps"] },
  { title: "Clean Code by Robert Martin", url: "https://www.amazon.in/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882", description: "The definitive guide to writing clean, maintainable code. Every developer should read this before writing production code.", field: "Technology", category: "Book", difficulty: "Intermediate", isFree: false, cost: "₹599", tags: ["Best Practices", "Software Engineering"] },
  { title: "Fireship YouTube Channel", url: "https://www.youtube.com/@Fireship", description: "Fast-paced, high-quality tech tutorials. Best for quickly understanding new technologies, frameworks, and concepts in under 10 minutes.", field: "Technology", category: "YouTube", difficulty: "Intermediate", isFree: true, tags: ["Web Dev", "JavaScript", "Quick Tutorials"] },

  // ── Business & Management ────────────────────────────────────────
  { title: "Google Project Management Certificate", url: "https://grow.google/certificates/project-management", description: "6-month Google certificate covering the full project lifecycle, Agile, Scrum, and real-world project tools. Recognised by employers.", field: "Business & Management", category: "Course", difficulty: "Beginner", isFree: false, cost: "₹3,000/month", tags: ["Project Management", "PMP", "Agile", "Google"], isPinned: true },
  { title: "Case Interview Prep — Victor Cheng", url: "https://www.caseinterview.com", description: "The most comprehensive free resource for consulting case interview preparation. Structured frameworks used by McKinsey, BCG, Bain candidates.", field: "Business & Management", category: "Article", difficulty: "Intermediate", isFree: true, tags: ["Consulting", "Case Interview", "McKinsey"] },
  { title: "Thinking in Bets by Annie Duke", url: "https://www.amazon.in/Thinking-Bets-Making-Smarter-Decisions/dp/0525557359", description: "Teaches decision-making under uncertainty — essential for managers and business leaders. Changes how you think about outcomes and choices.", field: "Business & Management", category: "Book", difficulty: "Beginner", isFree: false, cost: "₹450", tags: ["Decision Making", "Strategy", "Leadership"] },
  { title: "Notion for Teams", url: "https://www.notion.so", description: "The all-in-one workspace for project management, documentation, wikis, and team collaboration. Free for personal use.", field: "Business & Management", category: "Tool", difficulty: "Beginner", isFree: true, tags: ["Productivity", "Project Management", "Collaboration"] },
  { title: "Lenny's Newsletter", url: "https://www.lennysnewsletter.com", description: "The most-read newsletter for product managers and business professionals. Weekly insights on product strategy, metrics, and career growth.", field: "Business & Management", category: "Article", difficulty: "Intermediate", isFree: true, tags: ["Product Management", "Strategy", "Newsletter"] },

  // ── Finance & Accounting ─────────────────────────────────────────
  { title: "CFA Institute Learning Ecosystem", url: "https://www.cfainstitute.org/en/programs/cfa/curriculum", description: "Official CFA curriculum covering portfolio management, equity, fixed income, derivatives, and ethics. The gold standard for finance education.", field: "Finance & Accounting", category: "Course", difficulty: "Advanced", isFree: false, cost: "₹60,000/year", tags: ["CFA", "Investments", "Portfolio Management"], isPinned: true },
  { title: "Investopedia", url: "https://www.investopedia.com", description: "The internet's largest financial education resource. Covers everything from basics like compound interest to advanced derivatives and valuation.", field: "Finance & Accounting", category: "Article", difficulty: "Beginner", isFree: true, tags: ["Finance Basics", "Investing", "Economics"] },
  { title: "The Intelligent Investor by Benjamin Graham", url: "https://www.amazon.in/Intelligent-Investor-English-Benjamin-Graham/dp/0062312685", description: "Warren Buffett's favourite book and the bible of value investing. Essential reading for anyone pursuing finance, investing, or wealth management.", field: "Finance & Accounting", category: "Book", difficulty: "Intermediate", isFree: false, cost: "₹550", tags: ["Investing", "Value Investing", "Stock Market"] },
  { title: "Zerodha Varsity", url: "https://zerodha.com/varsity", description: "India's best free resource for learning stock markets, trading, and personal finance from scratch. Written for Indian investors and markets.", field: "Finance & Accounting", category: "Course", difficulty: "Beginner", isFree: true, tags: ["Stock Market", "Trading", "Indian Finance"] },
  { title: "Wall Street Prep", url: "https://www.wallstreetprep.com/knowledge", description: "Free financial modelling tutorials used by investment banks to train analysts. Covers DCF, LBO, M&A, and Excel modelling.", field: "Finance & Accounting", category: "Course", difficulty: "Advanced", isFree: true, tags: ["Financial Modelling", "Investment Banking", "Excel"] },

  // ── Law & Legal ──────────────────────────────────────────────────
  { title: "SCC Online", url: "https://www.scconline.com", description: "India's most comprehensive legal database — Supreme Court cases, High Court judgements, statutes, and legal commentary. Essential for Indian lawyers.", field: "Law & Legal", category: "Tool", difficulty: "Intermediate", isFree: false, cost: "₹5,000/year", tags: ["Case Law", "Indian Law", "Legal Research"], isPinned: true },
  { title: "Indian Kanoon", url: "https://indiankanoon.org", description: "Free search engine for Indian court judgements — Supreme Court, High Courts, and Tribunals. Best free alternative to paid databases.", field: "Law & Legal", category: "Tool", difficulty: "Beginner", isFree: true, tags: ["Indian Law", "Case Law", "Free Research"] },
  { title: "Introduction to Corporate Law — Coursera", url: "https://www.coursera.org/learn/corporate-law", description: "Beginner-friendly overview of corporate law, company structures, contracts, and governance. Good starting point for law students entering corporate practice.", field: "Law & Legal", category: "Course", difficulty: "Beginner", isFree: true, tags: ["Corporate Law", "Company Law", "Contracts"] },
  { title: "The Art of Advocacy by Noah Messing", url: "https://www.amazon.in/Art-Advocacy-Briefs-Motions-Compliance/dp/0190079487", description: "Practical guide to legal writing, drafting briefs, and oral arguments. Used by law students and junior lawyers at top firms.", field: "Law & Legal", category: "Book", difficulty: "Intermediate", isFree: false, cost: "₹2,500", tags: ["Legal Writing", "Advocacy", "Litigation"] },
  { title: "Law School Transparency", url: "https://www.lawschooltransparency.com", description: "Data-driven resource for understanding legal career outcomes, salary data, bar passage rates, and law school rankings.", field: "Law & Legal", category: "Article", difficulty: "Beginner", isFree: true, tags: ["Law School", "Career Data", "Bar Exam"] },

  // ── Arts & Design ────────────────────────────────────────────────
  { title: "Google UX Design Certificate", url: "https://grow.google/certificates/ux-design", description: "7-course UX design certificate by Google. Covers user research, wireframing, prototyping, and portfolio building. Recognised by top companies.", field: "Arts & Design", category: "Course", difficulty: "Beginner", isFree: false, cost: "₹3,000/month", tags: ["UX Design", "UI", "Figma", "Google"], isPinned: true },
  { title: "Figma — Free for Students", url: "https://www.figma.com/education", description: "The industry-standard design tool for UI/UX designers. Free for students and educators. Use it to build your entire design portfolio.", field: "Arts & Design", category: "Tool", difficulty: "Beginner", isFree: true, tags: ["UI Design", "Prototyping", "Design Tool"] },
  { title: "Behance", url: "https://www.behance.net", description: "The world's largest creative portfolio platform. Essential for designers to showcase work, find inspiration, and get discovered by employers.", field: "Arts & Design", category: "Tool", difficulty: "Beginner", isFree: true, tags: ["Portfolio", "Creative Work", "Inspiration"] },
  { title: "The Design of Everyday Things", url: "https://www.amazon.in/Design-Everyday-Things-Donald-Norman/dp/0465050654", description: "The bible of UX design thinking. Don Norman's timeless book on why good design is invisible and bad design is everywhere.", field: "Arts & Design", category: "Book", difficulty: "Beginner", isFree: false, cost: "₹650", tags: ["UX Principles", "Design Thinking", "Classic"] },
  { title: "Flux Academy YouTube", url: "https://www.youtube.com/@FluxAcademy", description: "High-quality web design and UX tutorials. Covers Figma, design principles, freelancing, and building a design career from scratch.", field: "Arts & Design", category: "YouTube", difficulty: "Beginner", isFree: true, tags: ["Web Design", "Figma", "Freelancing"] },

  // ── Marketing & Media ────────────────────────────────────────────
  { title: "Google Digital Marketing Certificate", url: "https://grow.google/certificates/digital-marketing-ecommerce", description: "Comprehensive 6-month certificate covering SEO, SEM, email marketing, social media, and analytics. Free to audit, paid for certificate.", field: "Marketing & Media", category: "Course", difficulty: "Beginner", isFree: false, cost: "₹3,000/month", tags: ["Digital Marketing", "SEO", "Google Ads"], isPinned: true },
  { title: "HubSpot Academy", url: "https://academy.hubspot.com", description: "Free certifications in inbound marketing, content marketing, email, SEO, and social media. Recognised globally and completely free.", field: "Marketing & Media", category: "Course", difficulty: "Beginner", isFree: true, tags: ["Inbound Marketing", "Content", "Free Certificate"] },
  { title: "Moz Beginner's Guide to SEO", url: "https://moz.com/beginners-guide-to-seo", description: "The most comprehensive free SEO guide on the internet. Covers keyword research, on-page SEO, link building, and technical SEO from scratch.", field: "Marketing & Media", category: "Article", difficulty: "Beginner", isFree: true, tags: ["SEO", "Search Engine", "Organic Traffic"] },
  { title: "Contagious by Jonah Berger", url: "https://www.amazon.in/Contagious-Things-Catch-Jonah-Berger/dp/1471111709", description: "Science of why things go viral. Essential reading for content marketers, brand managers, and anyone who wants to understand what makes content spread.", field: "Marketing & Media", category: "Book", difficulty: "Beginner", isFree: false, cost: "₹399", tags: ["Viral Marketing", "Brand Strategy", "Content"] },
  { title: "Marketing Examples Newsletter", url: "https://marketingexamples.com", description: "Real-world marketing case studies broken down simply. Great for learning what works in growth marketing, copywriting, and customer acquisition.", field: "Marketing & Media", category: "Article", difficulty: "Beginner", isFree: true, tags: ["Case Studies", "Growth Marketing", "Copywriting"] },

  // ── Healthcare & Medicine ────────────────────────────────────────
  { title: "Coursera — Science of Well-Being (Yale)", url: "https://www.coursera.org/learn/the-science-of-well-being", description: "Yale's most popular course ever, taken by 4M+ people. Covers the psychology of happiness and evidence-based well-being strategies.", field: "Healthcare & Medicine", category: "Course", difficulty: "Beginner", isFree: true, tags: ["Psychology", "Well-being", "Mental Health", "Yale"] },
  { title: "AMBOSS Medical Knowledge", url: "https://www.amboss.com", description: "Comprehensive medical knowledge platform used by medical students worldwide for USMLE, NEET PG, and clinical exam preparation.", field: "Healthcare & Medicine", category: "Tool", difficulty: "Intermediate", isFree: false, cost: "$30/month", tags: ["USMLE", "NEET PG", "Medical Exams"], isPinned: true },
  { title: "Geeky Medics", url: "https://geekymedics.com", description: "Free clinical skills guides, OSCE checklists, and medical revision resources. Used by thousands of medical students globally.", field: "Healthcare & Medicine", category: "Article", difficulty: "Beginner", isFree: true, tags: ["Clinical Skills", "OSCE", "Medical Students"] },
  { title: "Being Mortal by Atul Gawande", url: "https://www.amazon.in/Being-Mortal-Medicine-What-Matters/dp/1250076226", description: "A surgeon's powerful book on aging, dying, and what matters most in medicine. Essential reading for all healthcare professionals.", field: "Healthcare & Medicine", category: "Book", difficulty: "Beginner", isFree: false, cost: "₹450", tags: ["Medical Ethics", "Geriatrics", "Healthcare System"] },
  { title: "Medscape", url: "https://www.medscape.com", description: "Free medical news, clinical reference, drug information, and CME resources for healthcare professionals. Updated daily.", field: "Healthcare & Medicine", category: "Article", difficulty: "Intermediate", isFree: true, tags: ["Clinical Reference", "Medical News", "CME"] },

  // ── Engineering (Non-CS) ─────────────────────────────────────────
  { title: "MIT OpenCourseWare Engineering", url: "https://ocw.mit.edu/search/?d=Mechanical+Engineering", description: "Free MIT engineering course materials — lectures, assignments, exams. Covers Mechanical, Civil, Electrical, Chemical Engineering and more.", field: "Engineering (Non-CS)", category: "Course", difficulty: "Advanced", isFree: true, tags: ["MIT", "Mechanical", "Civil", "Electrical"], isPinned: true },
  { title: "GrabCAD Community", url: "https://grabcad.com/library", description: "Largest free library of CAD models shared by engineers worldwide. Great for learning CAD design and finding reference models for projects.", field: "Engineering (Non-CS)", category: "Tool", difficulty: "Intermediate", isFree: true, tags: ["CAD", "3D Models", "Engineering Design"] },
  { title: "Engineering Explained YouTube", url: "https://www.youtube.com/@EngineeringExplained", description: "Clear, well-researched explanations of mechanical and automotive engineering concepts. Perfect for both students and working engineers.", field: "Engineering (Non-CS)", category: "YouTube", difficulty: "Beginner", isFree: true, tags: ["Mechanical Engineering", "Automotive", "Concepts"] },
  { title: "Practical Guide to Six Sigma", url: "https://www.isixsigma.com", description: "Comprehensive resource for Six Sigma, Lean manufacturing, and quality management. Includes templates, tools, and certification guides.", field: "Engineering (Non-CS)", category: "Article", difficulty: "Intermediate", isFree: true, tags: ["Six Sigma", "Lean", "Quality Management"] },
  { title: "The Goal by Eliyahu Goldratt", url: "https://www.amazon.in/Goal-Process-Ongoing-Improvement/dp/0884271951", description: "A novel that teaches manufacturing and operations management through story. Essential reading for any engineer moving into management.", field: "Engineering (Non-CS)", category: "Book", difficulty: "Beginner", isFree: false, cost: "₹500", tags: ["Operations", "Manufacturing", "TOC"] },

  // ── Education ────────────────────────────────────────────────────
  { title: "Coursera — Learning How to Learn", url: "https://www.coursera.org/learn/learning-how-to-learn", description: "The world's most enrolled online course. Evidence-based techniques for learning anything faster — memory, focus, procrastination, and chunking.", field: "Education", category: "Course", difficulty: "Beginner", isFree: true, tags: ["Learning Techniques", "Memory", "Study Skills"], isPinned: true },
  { title: "Khan Academy for Educators", url: "https://www.khanacademy.org/teacher", description: "Free tools for teachers to assign content, track student progress, and personalise learning. Used in thousands of classrooms worldwide.", field: "Education", category: "Tool", difficulty: "Beginner", isFree: true, tags: ["Teaching", "EdTech", "Student Progress"] },
  { title: "Make It Stick by Peter Brown", url: "https://www.amazon.in/Make-Stick-Science-Successful-Learning/dp/0674729013", description: "Science-backed strategies for effective teaching and learning. Covers retrieval practice, interleaving, and spaced repetition for educators.", field: "Education", category: "Book", difficulty: "Beginner", isFree: false, cost: "₹499", tags: ["Teaching Methods", "Learning Science", "Pedagogy"] },
  { title: "Edutopia", url: "https://www.edutopia.org", description: "Research-based articles and videos on what works in education. Covers project-based learning, social-emotional learning, and classroom management.", field: "Education", category: "Article", difficulty: "Beginner", isFree: true, tags: ["Teaching Strategies", "Classroom", "Research-based"] },
  { title: "Articulate 360 for Educators", url: "https://articulate.com/360", description: "Industry-standard e-learning authoring tool for creating interactive online courses. Free trial available, used by corporate trainers and educators.", field: "Education", category: "Tool", difficulty: "Intermediate", isFree: false, cost: "$1,299/year", tags: ["E-learning", "Course Creation", "Instructional Design"] },

  // ── Science & Research ───────────────────────────────────────────
  { title: "Google Scholar", url: "https://scholar.google.com", description: "Free academic search engine covering millions of peer-reviewed papers, theses, books, and conference papers across all scientific fields.", field: "Science & Research", category: "Tool", difficulty: "Beginner", isFree: true, tags: ["Research Papers", "Academic", "Literature Review"], isPinned: true },
  { title: "Research Methods in Psychology — Coursera", url: "https://www.coursera.org/learn/research-methods", description: "Covers the fundamentals of research design, hypothesis testing, data collection, and scientific reporting. Applicable across all research fields.", field: "Science & Research", category: "Course", difficulty: "Beginner", isFree: true, tags: ["Research Methods", "Statistics", "Scientific Writing"] },
  { title: "Sci-Hub", url: "https://sci-hub.se", description: "Access to millions of research papers free of charge. Widely used by researchers in developing countries where journal access is limited.", field: "Science & Research", category: "Tool", difficulty: "Beginner", isFree: true, tags: ["Research Papers", "Open Access", "Academic"] },
  { title: "Statistics Done Wrong by Alex Reinhart", url: "https://www.statisticsdonewrong.com", description: "Free online book covering the most common statistical mistakes in research. Essential for anyone analysing data or reading scientific papers.", field: "Science & Research", category: "Book", difficulty: "Intermediate", isFree: true, tags: ["Statistics", "Research Methods", "Data Analysis"] },
  { title: "Nature Career Advice", url: "https://www.nature.com/nature/articles?type=career-feature", description: "Career guidance articles from Nature — the world's leading science journal. Covers PhD life, postdoc decisions, industry transitions, and grant writing.", field: "Science & Research", category: "Article", difficulty: "Intermediate", isFree: true, tags: ["Research Career", "PhD", "Academic Jobs"] },
];

// Clear existing seeded resources
await Resource.deleteMany({ status: "approved", submittedBy: adminId });

// Insert all resources
const docs = RESOURCES.map(r => ({ ...r, submittedBy: adminId, status: "approved", verifiedAt: new Date() }));
await Resource.insertMany(docs);

console.log(`✅ Seeded ${docs.length} resources across all fields`);
await mongoose.connection.close();